[build]
  command = "npm install --include=dev && npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20.12.2"
  # Removed NODE_ENV=production to allow devDependencies installation

[[plugins]]
  package = "@netlify/plugin-nextjs"