[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20.12.2"
  NODE_ENV = "production"

[[plugins]]
  package = "@netlify/plugin-nextjs"